/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shanmuk' at '14/4/16 2:59 AM' with Gradle 2.12
 *
 * @author shanmuk, @date 14/4/16 2:59 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
